Revamp Mac build scripts.

diff --git a/scripts/buildmac b/scripts/buildmac
--- a/scripts/buildmac
+++ b/scripts/buildmac
@@ -13,27 +13,27 @@ _=`basename $_`
 HERE=`pwd -P`/$_
 cd $s
 
-LIST=${HERE}/triples.txt
 LOGS=${HERE}/../logs
 BINS=${HERE}/../output
+OBJS=${HERE}/../build
 
 CSUF=cross
 
 KALE="${PATH}"
 
-# TODO: rewrite this script so that new buildmac is like buildall, current buildmac becomes like build
-make extract_all
-
 mkdir -p ${LOGS} ${BINS}
-for t in $(cat ${LIST} | grep -v "#"); do
-    [ -d ${BINS}/${t}-${CSUF} ] || make install \
-        TARGET=${t} OUTPUT=${BINS}/${t}-${CSUF} \
-        -j$(sysctl hw.logicalcpu | awk '{print $2}') 2>&1 \
-            | tee ${LOGS}/${t}-${CSUF}.log
-done;
 
-cd ${BINS}
-for t in $(find . -mindepth 1 -maxdepth 1 -type d); do
-    [ -h ${t}/usr ] || (cd ${t} && ln -s . usr)
-    [ -e ${t}.tgz ] || tar pczf ${t}.tgz ${t};
-done
+# CROSS BUILD
+[ -d ${BINS}/${1}-${CSUF} ] || make install \
+    TARGET=${1} OUTPUT=${BINS}/${1}-${CSUF} \
+    -j$(sysctl hw.logicalcpu | awk '{print $2}') 2>&1 | tee ${LOGS}/${1}-${CSUF}.log
+
+# CROSS PACKAGE
+[ -h ${BINS}/${1}-${CSUF}/usr ] || (cd ${BINS}/${1}-${CSUF} && ln -s . usr)
+[ -e ${BINS}/${1}-${CSUF}.tgz ] || (cd ${BINS} && tar pczf ${1}-${CSUF}.tgz ${1}-${CSUF})
+
+# CROSS CLEANUP
+rm -fr ${OBJS}/local/${1}
+
+# DIRECTORY CLEANUP
+rm -fr ${BINS}/${1}-${CSUF};
